baseurl = "https://rchoudhary.github.io"
languageCode = "en"
title = "Null Pointers"
theme = "kiss"

# Number of posts per page
Paginate = 10
enableRobotsTXT = true

[Author]
name = "Rutvik Choudhary"

[params.assets]
customCSS = ["css/custom.css"]

[taxonomies]
tag ="tags"

[params.info]
enableSocial = true

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    style = "github"
    lineNos = true
  [markup.tableOfContents]
    endLevel = 1
    ordered = true
    startLevel = 1