name: Deploy Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.91.2"
          
      - name: Build
        run: hugo -t kiss
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: rchoudhary/rchoudhary.github.io
          publish_dir: ./public
          user_name: rchoudhary
          user_email: 4595638+rchoudhary@users.noreply.github.com
          publish_branch: master
